<?php
$stmt = $pdo->prepare('SELECT * FROM form_payment_lots WHERE tenant_id = ? AND form_id = ? ORDER BY sort_order ASC, id ASC');
$stmt->execute([$tenantId, $formId]);
$paymentLots = $stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt = $pdo->prepare('SELECT * FROM form_discount_coupons WHERE tenant_id = ? AND form_id = ? ORDER BY is_active DESC, created_at DESC, id DESC');
$stmt->execute([$tenantId, $formId]);
$discountCoupons = $stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt = $pdo->prepare('SELECT * FROM form_group_discounts WHERE tenant_id = ? AND form_id = ? ORDER BY min_people ASC, id ASC');
$stmt->execute([$tenantId, $formId]);
$groupDiscounts = $stmt->fetchAll(PDO::FETCH_ASSOC);

function pricingAdminDiscountLabel(string $type, float $value): string
{
    return $type === 'percentage'
        ? rtrim(rtrim(number_format($value, 2, ',', '.'), '0'), ',') . '%'
        : 'R$ ' . number_format($value, 2, ',', '.');
}
?>
<style>
    .pricing-stack{display:grid;gap:20px}.pricing-card{border:1px solid #CECECE;border-radius:14px;background:#fff;overflow:hidden}.pricing-card-head{padding:22px 24px;border-bottom:1px solid #CECECE;display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.pricing-card-head h2{font-size:18px;font-weight:800;margin:0 0 4px}.pricing-card-head p{font-size:13px;color:#555555;margin:0}.pricing-card-body{padding:22px 24px}.pricing-items{display:grid;gap:10px}.pricing-item{border:1px solid #CECECE;border-radius:12px;padding:14px 16px;background:#F3F3F3}.pricing-item-main{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.pricing-item-title{font-weight:800;color:#1e293b}.pricing-item-meta{font-size:12px;color:#555555;margin-top:4px;line-height:1.5}.pricing-item-actions{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.pricing-badge{display:inline-flex;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800}.pricing-badge.active{background:#dcfce7;color:#166534}.pricing-badge.inactive{background:#CECECE;color:#555555}.pricing-editor{border-top:1px solid #CECECE;margin-top:12px;padding-top:14px}.pricing-editor summary{cursor:pointer;color:#212121;font-size:13px;font-weight:800;list-style:none}.pricing-editor summary::-webkit-details-marker{display:none}.pricing-editor[open] summary{margin-bottom:14px}.pricing-new{border:1px dashed #CECECE;border-radius:12px;padding:16px;background:#fff}.pricing-new>summary{cursor:pointer;font-weight:800;color:#212121}.pricing-help{font-size:12px;color:#555555}.pricing-empty{text-align:center;padding:18px;color:#555555;border:1px dashed #CECECE;border-radius:12px}@media(max-width:767px){.pricing-card-head,.pricing-card-body{padding:18px}.pricing-item-main{flex-direction:column}.pricing-item-actions{width:100%}}
</style>
<div class="col-12"><div class="pricing-stack">
    <section class="pricing-card"><div class="pricing-card-head"><div><h2>Configuração principal</h2><p>O valor por pessoa é usado quando não existem lotes ativos configurados.</p></div></div><div class="pricing-card-body">
        <form method="post" class="row g-3">
            <input type="hidden" name="action" value="update_payment"><input type="hidden" name="tab" value="payment">
            <div class="col-md-4"><label class="form-label" for="payment_amount">Valor-base por pessoa</label><input type="number" min="0" step="0.01" class="form-control" name="payment_amount" id="payment_amount" value="<?= htmlspecialchars($_POST['payment_amount'] ?? $form['payment_amount'] ?? '0.00') ?>" placeholder="25.00"></div>
            <?php $selectedPaymentMethods = explode(',', (string) ($_POST['payment_methods'] ?? $form['payment_methods'] ?? '')); ?>
            <div class="col-md-8"><label class="form-label">Formas aceitas</label><div class="d-flex flex-wrap gap-3"><?php foreach (['pix' => 'Pix', 'transferencia' => 'Transferência', 'dinheiro' => 'Dinheiro'] as $methodValue => $methodLabel): ?><label class="form-check"><input class="form-check-input" type="checkbox" name="payment_methods[]" value="<?= $methodValue ?>" <?= in_array($methodValue, $selectedPaymentMethods, true) ? 'checked' : '' ?>> <?= $methodLabel ?></label><?php endforeach; ?></div></div>
            <div class="col-md-6"><label class="form-label" for="pix_key">Chave Pix</label><input type="text" class="form-control" name="pix_key" id="pix_key" value="<?= htmlspecialchars($_POST['pix_key'] ?? $form['pix_key'] ?? '') ?>" placeholder="CPF, e-mail, telefone ou chave aleatória"></div>
            <div class="col-md-6"><label class="form-label" for="payment_whatsapp">WhatsApp para comprovantes</label><input type="tel" class="form-control" name="payment_whatsapp" id="payment_whatsapp" value="<?= htmlspecialchars($_POST['payment_whatsapp'] ?? $form['payment_whatsapp'] ?? '') ?>" placeholder="5511999999999" inputmode="tel"><div class="pricing-help mt-1">Informe DDI + DDD + número. Números brasileiros sem DDI recebem 55 automaticamente.</div></div>
            <div class="col-12"><label class="form-label" for="payment_instructions">Instruções adicionais</label><textarea class="form-control" name="payment_instructions" id="payment_instructions" rows="3" placeholder="Ex: Enviar comprovante no WhatsApp."><?= htmlspecialchars($_POST['payment_instructions'] ?? $form['payment_instructions'] ?? '') ?></textarea></div>
            <div class="col-12"><button type="submit" class="btn btn-primary">Salvar pagamento</button></div>
        </form>
    </div></section>

    <section class="pricing-card"><div class="pricing-card-head"><div><h2>Lotes</h2><p>Cada lote pode ter preço, período e quantidade de vagas próprios. O primeiro lote disponível pela ordem será aplicado.</p></div><span class="badge text-bg-light border"><?= count($paymentLots) ?></span></div><div class="pricing-card-body">
        <?php if ($paymentLots): ?><div class="pricing-items mb-3"><?php foreach ($paymentLots as $lot): ?>
            <?php $remaining = $lot['capacity'] === null ? null : max(0, (int) $lot['capacity'] - (int) $lot['used_quantity']); ?>
            <article class="pricing-item"><div class="pricing-item-main"><div><div class="pricing-item-title"><?= htmlspecialchars($lot['name']) ?> · R$ <?= number_format((float) $lot['price'], 2, ',', '.') ?></div><div class="pricing-item-meta"><?= $lot['starts_at'] ? 'De ' . date('d/m/Y H:i', strtotime($lot['starts_at'])) : 'Início imediato' ?> · <?= $lot['ends_at'] ? 'até ' . date('d/m/Y H:i', strtotime($lot['ends_at'])) : 'sem encerramento' ?><br><?= $lot['capacity'] === null ? 'Vagas ilimitadas' : (int) $lot['used_quantity'] . ' utilizadas · ' . $remaining . ' restantes' ?> · Ordem <?= (int) $lot['sort_order'] ?></div></div><div class="pricing-item-actions"><span class="pricing-badge <?= $lot['is_active'] ? 'active' : 'inactive' ?>"><?= $lot['is_active'] ? 'Ativo' : 'Inativo' ?></span><form method="post" data-confirm="Remover este lote? Lotes utilizados serão apenas desativados."><input type="hidden" name="action" value="delete_lot"><input type="hidden" name="lot_id" value="<?= (int) $lot['id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit">Remover</button></form></div></div>
                <details class="pricing-editor"><summary>Editar lote</summary><form method="post" class="row g-3"><input type="hidden" name="action" value="save_lot"><input type="hidden" name="lot_id" value="<?= (int) $lot['id'] ?>"><div class="col-md-4"><label class="form-label">Nome</label><input class="form-control" name="lot_name" maxlength="120" value="<?= htmlspecialchars($lot['name']) ?>" required></div><div class="col-md-3"><label class="form-label">Valor por pessoa</label><input class="form-control" type="number" min="0" step="0.01" name="lot_price" value="<?= htmlspecialchars($lot['price']) ?>" required></div><div class="col-md-2"><label class="form-label">Vagas</label><input class="form-control" type="number" min="1" name="lot_capacity" value="<?= htmlspecialchars((string) $lot['capacity']) ?>" placeholder="Ilimitadas"></div><div class="col-md-2"><label class="form-label">Ordem</label><input class="form-control" type="number" min="0" name="lot_sort_order" value="<?= (int) $lot['sort_order'] ?>"></div><div class="col-md-6"><label class="form-label">Início</label><input class="form-control" type="datetime-local" name="lot_starts_at" value="<?= htmlspecialchars(formatDateTimeLocal($lot['starts_at'])) ?>"></div><div class="col-md-6"><label class="form-label">Encerramento</label><input class="form-control" type="datetime-local" name="lot_ends_at" value="<?= htmlspecialchars(formatDateTimeLocal($lot['ends_at'])) ?>"></div><div class="col-12 d-flex justify-content-between align-items-center"><label class="form-check"><input class="form-check-input" type="checkbox" name="lot_is_active" <?= $lot['is_active'] ? 'checked' : '' ?>> Ativo</label><button class="btn btn-primary btn-sm" type="submit">Atualizar lote</button></div></form></details>
            </article>
        <?php endforeach; ?></div><?php else: ?><div class="pricing-empty mb-3">Nenhum lote configurado. O valor-base está sendo usado.</div><?php endif; ?>
        <details class="pricing-new"><summary>+ Adicionar lote</summary><form method="post" class="row g-3 mt-1"><input type="hidden" name="action" value="save_lot"><div class="col-md-4"><label class="form-label">Nome</label><input class="form-control" name="lot_name" maxlength="120" placeholder="1º lote" required></div><div class="col-md-3"><label class="form-label">Valor por pessoa</label><input class="form-control" type="number" min="0" step="0.01" name="lot_price" required></div><div class="col-md-3"><label class="form-label">Quantidade de vagas</label><input class="form-control" type="number" min="1" name="lot_capacity" placeholder="Ilimitadas"></div><div class="col-md-2"><label class="form-label">Ordem</label><input class="form-control" type="number" min="0" name="lot_sort_order" value="0"></div><div class="col-md-6"><label class="form-label">Início</label><input class="form-control" type="datetime-local" name="lot_starts_at"></div><div class="col-md-6"><label class="form-label">Encerramento</label><input class="form-control" type="datetime-local" name="lot_ends_at"></div><div class="col-12 d-flex justify-content-between align-items-center"><label class="form-check"><input class="form-check-input" type="checkbox" name="lot_is_active" checked> Ativo</label><button class="btn btn-primary" type="submit">Adicionar lote</button></div></form></details>
    </div></section>

    <section class="pricing-card"><div class="pricing-card-head"><div><h2>Cupons de desconto</h2><p>Escolha se o cupom vale para toda a inscrição ou individualmente para cada participante.</p></div><span class="badge text-bg-light border"><?= count($discountCoupons) ?></span></div><div class="pricing-card-body">
        <?php if ($discountCoupons): ?><div class="pricing-items mb-3"><?php foreach ($discountCoupons as $coupon): ?>
            <article class="pricing-item"><div class="pricing-item-main"><div><div class="pricing-item-title"><?= htmlspecialchars($coupon['code']) ?> · <?= htmlspecialchars(pricingAdminDiscountLabel($coupon['discount_type'], (float) $coupon['discount_value'])) ?></div><div class="pricing-item-meta"><?= ($coupon['application_scope'] ?? 'registration') === 'participant' ? 'Individual por participante' : 'Por inscrição' ?> · Mínimo de <?= (int) $coupon['min_people'] ?> pessoa(s) · <?= (int) $coupon['used_count'] ?> uso(s)<?= $coupon['max_uses'] !== null ? ' de ' . (int) $coupon['max_uses'] : ' · ilimitado' ?><?= $coupon['expires_at'] ? ' · expira em ' . date('d/m/Y H:i', strtotime($coupon['expires_at'])) : '' ?></div></div><div class="pricing-item-actions"><span class="pricing-badge <?= $coupon['is_active'] ? 'active' : 'inactive' ?>"><?= $coupon['is_active'] ? 'Ativo' : 'Inativo' ?></span><form method="post" data-confirm="Remover este cupom? Cupons utilizados serão apenas desativados."><input type="hidden" name="action" value="delete_coupon"><input type="hidden" name="coupon_id" value="<?= (int) $coupon['id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit">Remover</button></form></div></div>
                <details class="pricing-editor"><summary>Editar cupom</summary><form method="post" class="row g-3"><input type="hidden" name="action" value="save_coupon"><input type="hidden" name="coupon_id" value="<?= (int) $coupon['id'] ?>"><div class="col-md-4"><label class="form-label">Código</label><input class="form-control text-uppercase" name="coupon_code" value="<?= htmlspecialchars($coupon['code']) ?>" required></div><div class="col-md-4"><label class="form-label">Aplicação</label><select class="form-select" name="coupon_scope"><option value="registration" <?= ($coupon['application_scope'] ?? 'registration') === 'registration' ? 'selected' : '' ?>>Por inscrição</option><option value="participant" <?= ($coupon['application_scope'] ?? '') === 'participant' ? 'selected' : '' ?>>Individual por participante</option></select></div><div class="col-md-2"><label class="form-label">Tipo</label><select class="form-select" name="coupon_type"><option value="percentage" <?= $coupon['discount_type'] === 'percentage' ? 'selected' : '' ?>>Percentual</option><option value="fixed" <?= $coupon['discount_type'] === 'fixed' ? 'selected' : '' ?>>Valor fixo</option></select></div><div class="col-md-2"><label class="form-label">Desconto</label><input class="form-control" type="number" min="0.01" step="0.01" name="coupon_value" value="<?= htmlspecialchars($coupon['discount_value']) ?>" required></div><div class="col-md-3"><label class="form-label">Mín. pessoas</label><input class="form-control" type="number" min="1" max="20" name="coupon_min_people" value="<?= (int) $coupon['min_people'] ?>"></div><div class="col-md-3"><label class="form-label">Limite de usos</label><input class="form-control" type="number" min="1" name="coupon_max_uses" value="<?= htmlspecialchars((string) $coupon['max_uses']) ?>" placeholder="Ilimitado"></div><div class="col-md-3"><label class="form-label">Disponível a partir de</label><input class="form-control" type="datetime-local" name="coupon_starts_at" value="<?= htmlspecialchars(formatDateTimeLocal($coupon['starts_at'])) ?>"></div><div class="col-md-3"><label class="form-label">Expira em</label><input class="form-control" type="datetime-local" name="coupon_expires_at" value="<?= htmlspecialchars(formatDateTimeLocal($coupon['expires_at'])) ?>"></div><div class="col-12 d-flex justify-content-between align-items-center"><label class="form-check"><input class="form-check-input" type="checkbox" name="coupon_is_active" <?= $coupon['is_active'] ? 'checked' : '' ?>> Ativo</label><button class="btn btn-primary btn-sm" type="submit">Atualizar cupom</button></div></form></details>
            </article>
        <?php endforeach; ?></div><?php else: ?><div class="pricing-empty mb-3">Nenhum cupom cadastrado.</div><?php endif; ?>
        <details class="pricing-new"><summary>+ Adicionar cupom</summary><form method="post" class="row g-3 mt-1"><input type="hidden" name="action" value="save_coupon"><div class="col-md-4"><label class="form-label">Código</label><input class="form-control text-uppercase" name="coupon_code" placeholder="EVENTO10" required></div><div class="col-md-4"><label class="form-label">Aplicação</label><select class="form-select" name="coupon_scope"><option value="registration">Por inscrição</option><option value="participant">Individual por participante</option></select></div><div class="col-md-2"><label class="form-label">Tipo</label><select class="form-select" name="coupon_type"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></div><div class="col-md-2"><label class="form-label">Desconto</label><input class="form-control" type="number" min="0.01" step="0.01" name="coupon_value" required></div><div class="col-md-3"><label class="form-label">Mín. pessoas</label><input class="form-control" type="number" min="1" max="20" name="coupon_min_people" value="1"></div><div class="col-md-3"><label class="form-label">Limite de usos</label><input class="form-control" type="number" min="1" name="coupon_max_uses" placeholder="Ilimitado"></div><div class="col-md-3"><label class="form-label">Disponível a partir de</label><input class="form-control" type="datetime-local" name="coupon_starts_at"></div><div class="col-md-3"><label class="form-label">Expira em</label><input class="form-control" type="datetime-local" name="coupon_expires_at"></div><div class="col-12 d-flex justify-content-between align-items-center"><label class="form-check"><input class="form-check-input" type="checkbox" name="coupon_is_active" checked> Ativo</label><button class="btn btn-primary" type="submit">Adicionar cupom</button></div></form></details>
    </div></section>

    <section class="pricing-card"><div class="pricing-card-head"><div><h2>Desconto para grupos</h2><p>Cadastre faixas por quantidade. Quando mais de uma regra se aplicar, será usada a faixa com maior número mínimo de pessoas.</p></div><span class="badge text-bg-light border"><?= count($groupDiscounts) ?></span></div><div class="pricing-card-body">
        <?php if ($groupDiscounts): ?><div class="pricing-items mb-3"><?php foreach ($groupDiscounts as $discount): ?><article class="pricing-item"><div class="pricing-item-main"><div><div class="pricing-item-title">A partir de <?= (int) $discount['min_people'] ?> pessoas · <?= htmlspecialchars(pricingAdminDiscountLabel($discount['discount_type'], (float) $discount['discount_value'])) ?></div><div class="pricing-item-meta">Aplicado automaticamente sobre o subtotal da inscrição.</div></div><div class="pricing-item-actions"><span class="pricing-badge <?= $discount['is_active'] ? 'active' : 'inactive' ?>"><?= $discount['is_active'] ? 'Ativo' : 'Inativo' ?></span><form method="post"><input type="hidden" name="action" value="delete_group_discount"><input type="hidden" name="group_discount_id" value="<?= (int) $discount['id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit">Remover</button></form></div></div></article><?php endforeach; ?></div><?php else: ?><div class="pricing-empty mb-3">Nenhuma faixa de desconto configurada.</div><?php endif; ?>
        <details class="pricing-new"><summary>+ Adicionar ou atualizar faixa</summary><form method="post" class="row g-3 mt-1"><input type="hidden" name="action" value="save_group_discount"><div class="col-md-4"><label class="form-label">A partir de quantas pessoas?</label><input class="form-control" type="number" min="2" max="20" name="group_min_people" value="2" required></div><div class="col-md-4"><label class="form-label">Tipo</label><select class="form-select" name="group_discount_type"><option value="percentage">Percentual</option><option value="fixed">Valor fixo no total</option></select></div><div class="col-md-4"><label class="form-label">Desconto</label><input class="form-control" type="number" min="0.01" step="0.01" name="group_discount_value" required></div><div class="col-12 d-flex justify-content-between align-items-center"><label class="form-check"><input class="form-check-input" type="checkbox" name="group_is_active" checked> Ativo</label><button class="btn btn-primary" type="submit">Salvar faixa</button></div></form></details>
    </div></section>
</div></div>
