<?php $editing = isset($tenant); $value = fn($key,$default='') => htmlspecialchars($_POST[$key] ?? ($tenant[$key] ?? $default)); ?>
<h1 class="h3 mb-4"><?= $editing ? 'Editar empresa' : 'Criar empresa' ?></h1>
<?php if ($errors): ?><div class="alert alert-danger"><?php foreach($errors as $error): ?><div><?= htmlspecialchars($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<form method="post"><div class="card shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3">
<?php foreach ([['name','Nome da empresa',true],['slug','Slug',true],['document','Documento',false],['email','E-mail',false],['phone','Telefone',false],['logo','Logo (URL ou caminho)',false],['public_title','Título público',false],['public_subtitle','Subtítulo público',false]] as [$key,$label,$required]): ?><div class="col-md-6"><label class="form-label" for="<?= $key ?>"><?= $label ?></label><input class="form-control" id="<?= $key ?>" name="<?= $key ?>" value="<?= $value($key) ?>" <?= $required?'required':'' ?>></div><?php endforeach; ?>
<?php foreach ([['primary_color','Cor principal','#0d6efd'],['secondary_color','Cor secundária','#198754'],['background_color','Cor de fundo','#f6f7fb'],['text_color','Cor do texto','#111827'],['button_color','Cor do botão','#0d6efd']] as [$key,$label,$default]): ?><div class="col-md"><label class="form-label" for="<?= $key ?>"><?= $label ?></label><input type="color" class="form-control form-control-color w-100" id="<?= $key ?>" name="<?= $key ?>" value="<?= $value($key,$default) ?>"></div><?php endforeach; ?>
<div class="col-md-6"><label class="form-label">Estilo do formulário</label><select class="form-select" name="form_style"><?php foreach(['clean'=>'Clean','premium'=>'Premium','minimal'=>'Minimal','church'=>'Church','business'=>'Business'] as $key=>$label): ?><option value="<?= $key ?>" <?= $value('form_style','clean')===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div>
<div class="col-md-6 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="is_active" id="is_active" <?= (!isset($_POST['name']) ? (!$editing || $tenant['is_active']) : isset($_POST['is_active']))?'checked':'' ?>><label class="form-check-label" for="is_active">Empresa ativa</label></div></div></div></div></div>
<?php if (!$editing): ?><div class="card shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">Administrador inicial</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Nome</label><input class="form-control" name="admin_name" value="<?= htmlspecialchars($_POST['admin_name']??'') ?>" required></div><div class="col-md-4"><label class="form-label">E-mail</label><input type="email" class="form-control" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email']??'') ?>" required></div><div class="col-md-4"><label class="form-label">Senha inicial</label><input type="password" class="form-control" name="admin_password" minlength="8" required></div></div></div></div><?php endif; ?>
<div class="d-flex gap-2"><button class="btn btn-primary"><?= $editing?'Salvar alterações':'Criar empresa' ?></button><a class="btn btn-outline-secondary" href="system-tenants">Cancelar</a></div></form>
