<?php
$tenantSlug = trim((string) ($_GET['tenant'] ?? ''));
$backUrl = $tenantSlug !== '' ? appUrl('politica-de-privacidade', ['tenant' => $tenantSlug]) : appUrl('login');
?>
<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Política de Cookies · FormOps</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#334155;font-family:Arial,sans-serif}.page{width:min(920px,calc(100% - 24px));margin:24px auto 60px;background:#fff;border:1px solid #dbe6f3;border-radius:22px;overflow:hidden;box-shadow:0 20px 60px rgba(1,38,114,.1)}header{padding:32px;border-top:7px solid #04a09c;border-bottom:1px solid #e7eef7}main{padding:12px 32px 34px}h1,h2{color:#012672}h1{margin:0;font-size:38px}h2{font-size:19px;margin:0 0 8px}p,li{font-size:14px;line-height:1.7}.meta{color:#04a09c;font-weight:800}.section{padding:20px 0;border-top:1px solid #edf2f7}.section:first-child{border-top:0}.note{padding:14px;border-radius:10px;background:#eff6ff;border-left:4px solid #067ae3}.btn{display:inline-flex;margin-top:24px;padding:11px 15px;border-radius:10px;background:#012672;color:#fff;text-decoration:none;font-weight:800}@media(max-width:600px){header,main{padding-left:18px;padding-right:18px}h1{font-size:30px}.btn{width:100%;justify-content:center}}
</style></head><body><article class="page"><header><div class="meta">FormOps · versão <?= htmlspecialchars(FORMOPS_PRIVACY_POLICY_VERSION) ?></div><h1>Política de Cookies</h1><p>Esta política descreve cookies e tecnologias semelhantes usados pela plataforma para funcionamento, segurança e continuidade da experiência.</p></header><main>
<section class="section"><h2>Cookies essenciais</h2><p>O FormOps pode usar cookies de sessão estritamente necessários para autenticação, segurança, prevenção de uso indevido e funcionamento da aplicação. Esses recursos não têm finalidade publicitária.</p></section>
<section class="section"><h2>Armazenamento local</h2><p>Nos formulários públicos, o navegador pode armazenar localmente preferências de interface, como o aviso desta política, a aba ativa de inscrições com várias pessoas e, quando houver pagamento, o estado visual necessário para recuperar as instruções apresentadas após o envio.</p></section>
<section class="section"><h2>Serviços externos</h2><p>Alguns recursos podem carregar conteúdo de serviços externos, como bibliotecas de interface, geração de QR Code e links para aplicativos de comunicação. Ao acessar esses serviços, o fornecedor externo pode receber informações técnicas da conexão conforme suas próprias regras.</p></section>
<section class="section"><h2>Publicidade e perfilamento</h2><div class="note">Os formulários públicos do FormOps não ativam, por padrão, cookies de publicidade, remarketing ou perfilamento comportamental. Caso recursos opcionais desse tipo sejam adicionados futuramente, deverão ser tratados separadamente e, quando necessário, depender de escolha prévia do usuário.</div></section>
<section class="section"><h2>Como gerenciar</h2><p>O navegador permite apagar cookies e dados locais ou bloquear determinados armazenamentos. A desativação de recursos essenciais pode impedir login, manutenção de sessão ou funcionamento correto de partes da plataforma.</p></section>
<section class="section"><h2>Atualizações</h2><p>Esta política pode ser atualizada quando houver mudança relevante nas tecnologias utilizadas. A versão exibida no topo identifica o texto vigente.</p></section>
<a class="btn" href="<?= htmlspecialchars($backUrl) ?>">Voltar</a>
</main></article></body></html>
